### ISSUE TITLE
how to run robosuite reacher 

### ISSUE THREAD

**Issue by hskAlena** [voot-t/vild_code#1]
Hello,
I'm trying to reproduce robosuite reacher task.
So far, I've found out the command below seems to reproduce robosuite reacher task. 
`cd code; python vild_main.py --il_method vild --env_id 21 --rl_method trpo --vild_loss_type BCE`
I've also downloaded and unzipped RoboTurkPilot dataset under imitation_data folder.
But the thing is, I cannot find how to generate TRAJ-ID##.h5 file mentioned in code/core/irl.py
Where can I find that?

> Using (100, 100) relu networks.
Using CUDA.
adding key: robot-state
adding key: object-state
/home/user/gym/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
adding key: robot-state
adding key: object-state
State dim: 44, action dim: 7, action bound 1
Traceback (most recent call last):
  File "vild_main.py", line 370, in <module>
    main(args)
  File "vild_main.py", line 140, in main
    discriminator_updater = VILD(state_dim=state_dim, action_dim=action_dim, args=args, policy_updater=policy_updater)   # need entropy coefficient           
  File "/home/user/projects/vild_code/code/core/vild.py", line 8, in __init__
    super().__init__(state_dim, action_dim, args)
  File "/home/user/projects/vild_code/code/core/irl.py", line 18, in __init__
    self.load_demo_list(args, verbose=initialize_net)  
  **File "/home/user/projects/vild_code/code/core/irl.py", line 82, in load_demo_list
    hf = h5py.File(traj_filename + ".h5", 'r')**
  File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/user/.local/lib/python3.6/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = **'../imitation_data/TRAJ_robo/SawyerNutAssemblyRound_reach/SawyerNutAssemblyRound_reach_TRAJ-ID12.h5', errno = 2, error message = 'No such file or directory',** flags = 0, o_flags = 0)

Thanks a lot!!

**Comment by voot-t** [comment]
Hi,
Thanks for notifying the issue. I just now uploaded the correct h5 dataset in /imitation_data.

**Comment by hskAlena** [comment]
wow Thank you!!
